package it.unibo.objectmon.api.data;

import it.unibo.objectmon.api.data.type.DamageType;
import it.unibo.objectmon.api.data.type.ElementalType;

public class Skill {
    private final int id;
    private final String name;
    private final int basePower;
    private final int powerPointsMax;
    private final DamageType dmgType;
    private final ElementalType SkillType;
    private final int accuracy;
    private final int priority;

    private int powerPointsCurrent;
    
    /**
     *
     * @param id Id of the Skill. It should always be generated by the system, and not from user input.
     * @param name Name of the Skill. can't be empty or void.
     * @param basePower Base Power of the Skill, that gets used for the damage calculation in battle.
     * @param powerPointsMax Power Points of the skill. Represents how much a move can be used.
     * @param dmgType DamageType of the Skill. if PHYS use the Atk of the Objectmon, if SPEC use the SpAtk of the Objectmon, if STAT then it doesn't use the Stats of the Objectmon.
     * @param SkillType ElementalType of the Skill. Is used to determine various multipliers.
     * @param accuracy Accuracy of the Skill. A Skill will hit if a random number (0-100) is lower or equal to the accuracy. Accuracy can have values from -1 to 100 (-1 for Skills that can't miss).
     * @param priority Priority of the Skill. If a Skill has higher priority then there won't be a check for the  Objectmon's speed. If they have the same priority, then there will be a check for speed.
     */
    public Skill(final int id, final String name,final int basePower, final int powerPointsMax, final int priority, final DamageType dmgType, final ElementalType SkillType, final int accuracy) {
        this.id = id;
        this.name = name;
        this.basePower = basePower;
        this.powerPointsMax = powerPointsMax;
        this.powerPointsCurrent = powerPointsMax;
        this.priority = priority;
        this.dmgType = dmgType;
        this.SkillType = SkillType;
        this.accuracy = accuracy;
    }

    /**
     * 
     * @return Returns the id of the Skill.
     */
    public int getId() {
        return id;
    }

    /**
     * 
     * @return Returns the name of the Skill.
     */
    public String getName() {
        return name;
    }

    /**
     * 
     * @return Returns the basePower of the Skill.
     */
    public int getBasePower() {
        return basePower;
    }

    /**
     * 
     * @return Returns the damageType of the Skill.
     */
    public DamageType getDmgType() {
        return dmgType;
    }

    /**
     * 
     * @return Returns the ElementalType of the Skill.
     */
    public ElementalType getSkillType() {
        return SkillType;
    }

    /**
     * 
     * @return Returns the maximun powerPoint of the Skill.
     */
    public int getPowerPointsMax() {
        return powerPointsMax;
    }
    
    /**
     * 
     * @return Returns the accuracy of the Skill.
     */
    public int getAccuracy() {
        return accuracy;
    }

    /**
     * 
     * @return Returns the priority of the Skill.
     */
    public int getPriority() {
        return priority;
    }

    /**
     * 
     * @return Returns the current powerPoints of the Skill.
     */
    public int getPowerPointsCurrent() {
        return powerPointsCurrent;
    }

    public void resetPowerPointsCurrent(){
        this.powerPointsCurrent = this.powerPointsMax;
    }

    public void usePowerPointsCurrent(){
        if(canUseSkill()){
            this.powerPointsCurrent--;
        }
    }
    
    /**
     * 
     * @return Checks if a Skill can be used. If true then the Skill will be use, otherwise it can't be used.
     */
    public boolean canUseSkill(){
        return this.powerPointsCurrent != 0 ? true: false;
    }
    
}

